services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: fiap
      ME_CONFIG_BASICAUTH_PASSWORD: fiap2023
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo2023   
      ME_CONFIG_MONGODB_URL: mongodb://root:mongo2023@database:27017
    links:
      - database
    networks:
      - networks-fiap
    ports:
      - "8081:8081"      
  database:
    image: mongo
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo2023
    ports:
      - "27017:27017"
    volumes:
      - database_data:/data/db
    networks:
      - networks-fiap
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    container_name: backend
    environment:
      - NODE_ENV=development
    user: "node"
    volumes:
      - backend_data:/home/node/app
    networks:
      - networks-fiap  
    ports:
      - "3000:3000"            
networks: 
    networks-fiap:
      driver: bridge
volumes:
  database_data:
  backend_data: